### ISSUE TITLE
Hmd-D Nasals (16F04, 16F10, 16F14, 16F23)

### ISSUE THREAD

**Issue by cheuk879** [silnrsi/font-shimenkan#19]
The following nasal variants are needed for [hmdd]:

16F04: ![plrd-16f04-flat](https://user-images.githubusercontent.com/10625598/41582510-6f74db9a-73d4-11e8-8d4d-1aeb78cdb92c.gif) -- narrow with flat sides & round corners.
16F10: ![plrd-16f10-flat](https://user-images.githubusercontent.com/10625598/41582575-99c40ad8-73d4-11e8-80c5-37fd2be0b01a.gif) -- narrow with flat sides & round corners.
16F14: ![plrd-16f14-semicircle](https://user-images.githubusercontent.com/10625598/41582626-b950bcf2-73d4-11e8-9d58-7f1df2e40976.gif) -- resembles an enlarged Latin letter 'e'.
16F23: ![plrd-16f23-semicircle](https://user-images.githubusercontent.com/10625598/41582713-ee04ac38-73d4-11e8-81bb-725972095b5d.gif) -- resembles an enlarged Latin letter 'e' flipped vertically.

**Comment by jvgaultney** [comment]
Do these changes also need to be made for the warted versions (u16F05, u16F11, u16F15, u16F24)?

**Comment by cheuk879** [comment]
Yes, the **dotted** versions will use these same base glyphs as shown in the first comment.  We just add a dot to the upper right.

**Comment by jvgaultney** [comment]
Since these glyph variants are only for [hmdd] and would only ever appear dotted (rather than warted), I will make the default for these (such as u16F05.hmdd) dotted.

**Comment by cheuk879** [comment]
Only 16F15 is used solely by [hmdd].  The other 3 (16F05, 16F11, 16F24) are used by multiple groups in warted forms.  Accordingly, it would be best to keep the warted forms the default, at least for the 3.

**Comment by jvgaultney** [comment]
Keep in mind that this feature is *only* for [hmdd], as is the dotted feature (#20). So although other languages do use 16F05, 16F11, 16F24 they would never use these hmdd-specific forms. They would also not use dotted forms. Since [hmdd] would always want both this feature and the dotted feature turned on, we can make things easier by just making the .hmdd forms use the dot by default, and exclude them from the dotted feature (#20). 

Just to confirm again: Is there any situation where these hmdd-only forms would need to appear with the standard warts (non-dotted)?

**Comment by cheuk879** [comment]
Ah yes, the default **for this feature** can be the dotted forms.  And no, these forms are attested only with dots, not warts.

**Comment by jvgaultney** [comment]
Working now, but has been quite difficult:
![image](https://user-images.githubusercontent.com/4226750/53868926-054a4d80-3fef-11e9-81f2-1e93ff67a855.png)

These are not as narrow as the examples above, mainly because the style of the font the examples are taken from is a universally narrow style - where all the glyphs are quite narrow. To create these letters in the style of Shimenkan they needed to be a little bit wider to harmonize with the rest of the letters used by hmdd. When they were narrower they looked like they'd been substituted in using some other font, and it looked like something had gone wrong. Here are the forms in the context of others, and showing that the dotted (non-warted) forms are working:
![image](https://user-images.githubusercontent.com/4226750/53869180-94effc00-3fef-11e9-8794-6b7dde3f1b81.png)

![image](https://user-images.githubusercontent.com/4226750/53869248-bf41b980-3fef-11e9-82c7-16c663b32d26.png)
