### ISSUE TITLE
Align all shoulder-height vowels to be flush with tops of consonants

### ISSUE THREAD

**Issue by mhosken** [silnrsi/font-shimenkan#33]
Bai Yi (ygp?) For MIAO VOWEL SIGN AE (16F73) make the bottom vertical line descend below the baseline for the vowels.
![changes2](https://lh3.googleusercontent.com/LMBbedLcrbxIyiiCMmylmGAUjrR1SFkZZ5vnnWSS8WbyqQoJSVMIL83WrvKbT_FqdjQv1uPyTrq92HB67kQk3hK_b9NP6jj0Vp3gvZXZUrDGdHmCLH-n79PQ9zhvng3QmuT4TZxj)

**Comment by mhosken** [comment]
Flush top positioning

**Comment by jvgaultney** [comment]
Actually not needed for Bai Yi (ygp) but rather for hmd lpo ywq-a

**Comment by cheuk879** [comment]
Flush top for S is the preference across all groups that use the S position.  The only potential exception is ywq-b, for which we haven't been able to solicit any feedback.  See Future Miao Font Plan.

**Comment by cheuk879** [comment]
This applies to all finals.  It's ok for ascenders (16F5C, 16F74) to be higher as long as the box of the final is flush with the top side of the box of the base char.

**Comment by cheuk879** [comment]
List of all groups that use S: hmd, sfm, hmz, lpo, ywqa, ygp, yna
These all want finals at S to flush top.
hmdd has no S pos.
ywqb is not willing to ans questions.  We can just treat them the same as ywqa for now so that flush top becomes the default across all groups.  If it turns out later they are the odd one out, we can just switch on the overshoot for their lang-specific build then.

**Comment by cheuk879** [comment]
Pls. change subject line to say this is across all groups.

**Comment by jvgaultney** [comment]
Are you absolutely sure that no group (other than possibly yqwb) wants vowels positioned slightly higher? That goes against all the research done by me and others before me. If you can absolutely confirm this - and no turning back - then we can change the default and get rid of the higher alignment altogether.

**Comment by cheuk879** [comment]
Here are the facts: In 2018 spring I asked all user groups directly about their positioning preference for vowels at S position, showing them samples from different corpuses.  By May/June all but [hmdd] & [ywqb] replied with flush top preference.  This was recorded in the planning document & has remained as such ever since.  This March a request from another source reported [ygp] prefer overshoot positioning.  Since this is confusing, I asked [ygp] directly again.  By May/June this year, they replied confirming their flush top preference.  I also contacted that alternate source for clarification but haven't got any so far.

NB:  In most cases users are not basing their preferences on pre-existing publications but rather current needs.  In some cases behaviours in older materials are actually "wrong" or "not good enough" in their perception.

Since it has been mentioned a consensus would be necessary before proceeding, I'll defer to you for a decision.

**Comment by jvgaultney** [comment]
I can't make that decision for you, and will wait until everyone involved can agree.

**Comment by jvgaultney** [comment]
Current status (build 229): 
High - Default, [yna], [ygp], [sfm]
Flush top - [hmz], [hmd], [ywqa], [lpo], [hmdd]

[ygp], [yna], and default are pending decisions
@mhosken should probably take a look at switching [sfm] - I wasn't confident in doing that in the code

**Comment by cheuk879** [comment]
Actually [yna] has already confirmed flush top preference.  It's only [ygp] for whom we need to have consensus with the other feedback source.

**Comment by cheuk879** [comment]
And yes, [sfm] needs flush top, too (confirmed at least 2x).

**Comment by cheuk879** [comment]
Build 233 has flush top as default for all langs, which is perfect!  Hopefully we'll have confirmation along this line from the other feedback source of [ygp] soon.
