### ISSUE TITLE
[ywq] request for 16F12

### ISSUE THREAD

**Issue by kienwt** [silnrsi/font-shimenkan#41]
Team requests that 16F12 look more like the first glyph from BlkYi3.
![16F12](https://user-images.githubusercontent.com/18396131/57347236-2ca2cf80-7184-11e9-8acf-3e97914e4024.PNG)

**Comment by cheuk879** [comment]
Per user feedback 2019-06-11, it is the weight of the left glyph that is the main thing they want.  They are fine using the regular font for data entry for now as long as they can use the Book series when it comes out later.  (Samples of Shimenkan Test Regular vs Shimenkan Test Book Regular have been shown them.)

**Comment by jvgaultney** [comment]
It used to be more curved, but in an email on 2018-06-02 cheuk879 said "16F12 will need to be narrower; the upper stroke of the 'C' shape will need to be more straight (i.e., less curved)."

Do I need to change it back?

**Comment by cheuk879** [comment]
The 2018 version of the glyph was way too wide & curved, that's why the email comment relayed from the user.  The current shape has the right width, but they like the weight of BlkYi3.  In a later reply they did remark that on comparison the right glyph shown above had a "longer neck" than the left one.  It looks like the weight difference is giving this visual effect.  If so, then the book series should be able to resolve this issue.  But if it has to do with design/curvature, then some minor adjustments will need to be made.  Of course, it could be due to both factors, but I trust you are in a much better position to comment on this.

**Comment by jvgaultney** [comment]
I'll tweak it slightly one last time.

**Comment by jvgaultney** [comment]
Here's the latest, about halfway between the two:
![image](https://user-images.githubusercontent.com/4226750/61252918-22d6b300-a757-11e9-9d5b-8a91b6841616.png)
Please let me know if this is now OK.

**Comment by cheuk879** [comment]
Looks fine to me.  Will pass on to the users, but since their turn-around time often > 1 week, I'd say this version can be deemed acceptable for 1.0.
