### ISSUE TITLE
[hmd, yna] Re-enable kerning for V at F pos with no asp

### ISSUE THREAD

**Issue by cheuk879** [silnrsi/font-shimenkan#73]
(Red syllables) Kerning is lost in build 245:
![plrd-test-kern-hmd+yna-err-245](https://user-images.githubusercontent.com/10625598/62827765-4987de00-bb8b-11e9-92ae-533c164bd74e.png)
It should be like that in build 244:
![plrd-test-kern-hmd+yna-ok-244](https://user-images.githubusercontent.com/10625598/62827784-c61abc80-bb8b-11e9-9b47-d2ca96987c11.png)

**Comment by mhosken** [comment]
I must admit that this is the first I have heard that the behaviour regarding floor position tucking is different between whether there is an aspiration mark or not. We have been working on the assumption that such behaviour is the same regardless of whether there is an aspiration mark or not.

Does this also apply to the waist position or do we always shift that right? Are YNA and HMD in this respect? I'll tuck them for now until you tell me otherwise.

It is much more helpful in your example test strings to show examples with and without the apsiration mark than showing different bases and vowels, unless there is a difference in behaviour between certain bases and vowels that is irregular.

BTW what does the blue mean in the examples above? Some explanations would be nice to help clear through the mess.

**Comment by jvgaultney** [comment]
Still a problem in 258:
![image](https://user-images.githubusercontent.com/4226750/63084485-30907b80-bf43-11e9-90a0-9d202a32e78c.png)
![image](https://user-images.githubusercontent.com/4226750/63084508-3f772e00-bf43-11e9-8dc0-233a0c00c9ce.png)

**Comment by jvgaultney** [comment]
Confirmed working in build 261:

![image](https://user-images.githubusercontent.com/4226750/63098313-862c4e80-bf6a-11e9-80fa-98d51ec8a27c.png)
![image](https://user-images.githubusercontent.com/4226750/63098333-93e1d400-bf6a-11e9-9dec-4f469d588d10.png)
