### ISSUE TITLE
Flat version of 16F57

### ISSUE THREAD

**Issue by cheuk879** [silnrsi/font-shimenkan#8]
This form of 16F57 is needed for [hmz], [hmd], [lpo], & [hmdd]:

![plrd-16f57-flat](https://user-images.githubusercontent.com/10625598/41576581-bfd679dc-73ba-11e8-934d-b0d6a09f4974.gif)

The bottom is flat.  Given the round-bottom version is used by only 2 groups, it's better to make the flat version the default & the round one variant.

**Comment by jvgaultney** [comment]
That's a very subtle difference that will be rarely visible at text size. Here is normal:

![image](https://user-images.githubusercontent.com/4226750/41585452-015e776a-73a2-11e8-9acc-705593fec472.png)

And if this 'flatter' design is to become the default, then what is supposed to happen to related characters:

![image](https://user-images.githubusercontent.com/4226750/41585525-42265380-73a2-11e8-8172-39fc8859bd7a.png)

And if flat becomes the default it means that [yna] now needs their own unique font that is different from the default - in fact there would be no group that could use the default font. That seems odd. since all those four langs have unique needs in addition to this, I guess I now think it would be better to make the flat one an alternate.

*A better solution* might be to redesign the glyph to be acceptable to everyone, where it is slightly 'flatter' and between strong curved and strong flat versions, like this very rough mockup:

![image](https://user-images.githubusercontent.com/4226750/41585846-15ff6084-73a3-11e8-9c3f-882588ef55ca.png)

Would that work?

**Comment by cheuk879** [comment]
[yna] doesn't use this char, so we don't need to worry about them.
The flatness only applies to 16F57 & not to 16F58 or any ligated forms based on it.
None of the ligated forms based on 16F57 is in use (they either don't have this combo or write the finals separately), so we don't need to worry about them.

On flat vs round, the difference is quite conspicuous to me.  In fact, that was the first thing the hmd pointed out back in 2012 on examining the code chart.  Even a non-hmd participant was able to notice it (in her terminology, the flat version was like a 'duck').  Based on that, I believe the chance of a compromise being acceptable to all would be remote.

On default, either version can do.  I just suggested switching them based on the no. of groups using them so as to make it a bit simpler to build (fewer tailoring).  I'm fine with keeping the current way if that sounds better to you :)

**Comment by jvgaultney** [comment]
Working now for hmz hmd hmdd lpo

![image](https://user-images.githubusercontent.com/4226750/53868356-c962b880-3fed-11e9-90ef-933bdb4213d3.png)
