### ISSUE TITLE
Please clarify documentation

### ISSUE THREAD

**Issue by nim-nim** [silnrsi/font-shimenkan#84]
> The font family named simply 'Shimenkan' supports all languages through language-specific OpenType features.

Does this mean that, with sufficiently advanced OpenType support, the Shimenkan font files contained in Shimenkan-1.000.tar.xz are sufficient to provide all the glyphs created in this project, and all the other font families (ShimekanXXX) can just be aliased in fontconfig ?

Or does it mean that it only replaces the Shimekan XXX fonts (GSM, MAS…) ?

Will the glyphs in Shimenkan Guifan also be provided or are they an alternate, not accessible via OpenType features ? In that case the associated font files still need to be provided as stylistic alternate ?

**Comment by jvgaultney** [comment]
The main Shimenkan font has OpenType features that, when activated, provide all the alternates and positioning needed for all the languages. However the problem is that only very few applications provide an interface or other ways to control those features. The language-specific fonts have the appropriate features turned on by default, so do not need an interface to control them. All the fonts have the same set of glyphs in them - only the default features settings are different.

If you are only needing one language variant, and your application does not allow for language-specific feature control, then I'd suggest you use one of the language-specific ones (like Shimenkan Guifan). 

If you want to use it for multiple languages, and have a way to control the features, then you can use just Shimenkan.

**Comment by nim-nim** [comment]
Thank you very much for the information, that's exactly what I needed to know.

Then I'll tentatively only distribute the main font, knowing that some apps won't be able to use it to its full extent, and that it won't work for some users. The sad truth is that the only thing that forces apps to improve their OpenType support is unavailability of compatibility fonts.

So it's a choice between hurting users in the short term or hurting them in the long term :(
